config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :goods do
    resources :comments
  end
  #resources :givings
  get '/auth/:provider/callback' => 'sessions#create'
  post '/auth/signout' => "sessions#destroy"
  root :to=> "goods#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :goods
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :content
  belongs_to :user
  belongs_to :good
end

app/models/giving.rb
class Giving < Good
  def status_check
    self.status = "已送出"
    #self.save
  end
end

app/models/good.rb
class Good < ApplicationRecord
  def status_uncheck
    self.status = nil
    self.save
  end
  has_many :comments, :dependent => :destroy
  belongs_to :user
  belongs_to :category
  validates_presence_of :name
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "http://pic.pimg.tw/rieszliu/1174375311.jpg"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/lending.rb
class Lending < Good
    def status_check
    self.status = "已借出"
    #self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :goods
  has_many :comments, :dependent => :destroy
end

app/models/wanting.rb
class Wanting < Good
    def status_check
    self.status = "已徵得"
    #self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  protected

  def current_user
    if session[:user_id]
      User.find( session[:user_id] )
    else
      nil
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_good
  before_action :set_comments

  def create
    @comment = @good.comments.build(comment_params)
    if current_user == nil
      flash[:alert]="請先登入"
      #render "goods/show"
    else  @comment.user = current_user
      if @comment.save
        flash[:notice]="留言成功"
        #render "goods/show"
      else
        flash[:alert]="留言失敗"
        #render "goods/show"
      end
    end
    redirect_to good_path(@good)
  end
  def edit
    @comment = Comment.find(params[:id])
  end
  def update
    @comment = Comment.find(params[:id])
    if @comment.user == current_user
      @comment.update(comment_params)
      flash[:notice]="更新留言成功"
    elsif @comment.user != current_user
      flash[:alert]="沒有權限"
    else
      flash[:alert]="更新留言失敗"
    end
    render "goods/show"
  end
  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user !=current_user
      flash[:alert]="沒有權限"
    else
      @comment.destroy
    end
      redirect_to good_path(@good)
  end
  private
  def set_good
    @good = Good.find(params[:good_id])
  end
  def set_comments
    @comments = @good.comments
  end
  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end
end

app/controllers/givings_controller.rb
class GivingsController < ApplicationController
  def index
    @givings = Giving.all.page(params[:page]).per(10)
  end
  def new
    @giving = Giving.new
  end

  def create
    @giving = Giving.new(giving_params)
    @giving.save
    redirect_to givings_path
  end

  private
  def giving_params
    params.require(:giving).permit(:name, :description, :area, :type, :category_id)
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :user_login_check, :except => [:index]
  def index
    @goods = Good.includes(:category).order("created_at DESC").page(params[:page]).per(10)
  end

  def new
    @good = Good.new
  end

  def create
    @good = Good.new(good_params)
    @good.user = current_user
    @good.save
    redirect_to goods_path
  end

  def show
    @good = Good.includes(:category, :comments).find(params[:id])
    @comments = @good.comments.order("created_at DESC")
  end

  def edit
    @good = Good.find(params[:id])
    @good.status_check
    if @good.user !=current_user
      flash[:alert]="沒有權限"
      redirect_to goods_path
    end
  end

  def update
    @good = Good.find(params[:id])
    if params[:delete_pic]=="1"
      @good.picture=nil
    end
    if params[:status]=="1"
      @good.status_check
    end
    if @good.user == current_user
       @good.update(good_params)
       flash[:notice] = "更新成功"
       redirect_to goods_path
    elsif @good.user != current_user
       flash[:alert]="沒有權限"
       render :action => :edit
    else
       flash[:alert]="更新失敗"
       render :action => :edit
    end
  end

  def destroy
    @good = Good.find(params[:id])
    if @good.user !=current_user
      flash[:alert]="沒有權限"
    else
      @good.destroy
    end
      redirect_to goods_path
  end

  private
  def good_params
    params.require(:good).permit(:name, :description, :area, :type,
                                :status, :picture, :user_id, :category_id)
  end

  def user_login_check
    if current_user == nil
      flash[:alert]="請先登入"
      redirect_to goods_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    #Rails.logger.debug("------fb data------")
    #Rails.logger.debug( auth_hash.inspect )
    #Rails.logger.debug("===")
    #Rails.logger.debug( auth_hash[:uid] )
    #Rails.logger.debug( auth_hash[:info][:name] )
    #Rails.logger.debug( auth_hash[:info][:email] )
    #Rails.logger.debug( auth_hash[:info][:image] )

    #Rails.logger.debug( auth_hash[:credentials][:token] )
    #Rails.logger.debug( auth_hash[:credentials][:expires_at] )

    user = User.where( :fb_uid => auth_hash[:uid] ).first
    unless user
      user = User.new( :name => auth_hash[:info][:name],
                       :email => auth_hash[:info][:email],
                       :fb_image => auth_hash[:info][:image],
                       :fb_token => auth_hash[:credentials][:token],
                       :fb_expires_at => auth_hash[:credentials][:expires_at],
                       :fb_uid => auth_hash[:uid] )

      user.save!
    end

    session[:user_id] = user.id

    redirect_to root_path
  end

  def destroy
    reset_session

    redirect_to root_path
  end

  protected


  def auth_hash
    request.env['omniauth.auth']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # def user_login_check
  #   if current_user == nil
  #     flash[:alert]="請先登入"
  #     redirect_to goods_path
  #   end
  # end
  #試不出來
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/edit.html.erb
<h4>文章主題：<%= @good.name %></h4>
<h4>文章類別：<%= @good.category.name %></h4>
<h4>文章內容：<%= @good.description %></h4>
<table class="table">
 <thead>
    <th>留言內容</th>
   <th>留言者</th>
   <th>留言時間</th>
 </thead>
  <tbody>
    <% @good.comments.each do |c|%>
      <tr>
        <td><%=c.content%></td>
        <td><%=c.user.try(:name) %></td>
        <td><%=c.created_at.localtime.to_s(:db)%></td>
        <td><%=link_to "", good_comment_path(@good,c), :method =>:patch,:class =>"btn btn-info glyphicon glyphicon-pencil"%></td>
        <td><%=link_to "", good_comment_path(@good,c),:method =>:delete, :class =>"btn btn-danger glyphicon glyphicon-trash"%></td>
      </tr>
    <%end%>
  </tbody>
</table>
  <%=form_for @comment, :url => good_comment_path(@good,@comment), :method => :patch do |f| %>
    <%=f.label :content,"修改留言"%>
    <%=f.text_area :content, :class =>"form-control"%>
    <%=f.submit "修改留言", :class =>"btn btn-primary"%>
    <%= link_to "返回主頁", goods_path, :class =>"btn btn-default"%>
  <% end %>

app/views/givings/index.html.erb
<h1>烏托邦幫忙</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <td>物品名稱</td>
      <td>物品類別</td>
      <td>說明</td>
      <td>物品狀態</td>
    </tr>
  </thead>
  <tbody>
    <% @givings.each do |g| %>
    <tr>
      <td><%= g.name %></td>
      <td><%= g.type %></td>
      <td><%= g.description %></td>
      <td><%= g.status %></td>
    </tr>
    <% end %>
  </tbody>

</table>

app/views/givings/new.html.erb
<%= form_for @giving ,:url => givings_path do |f| %>
<div class="form-group">
  <%= f.label :name,"名稱" %>
  <%= f.text_field :name , :class => "form-control" %>
</div>
  <%= f.label :type, "物品期許" %>
  <%= f.text_field :type %>
  <%= f.collection_select(:category_id, Category.all, :id, :name,:include_blank => "please select" )%>
  <%= f.label :description, "說明" %>
  <%= f.text_field :description %>
  <%= f.label :area, "地區" %>
  <%= f.text_field :area %>
  <%= f.submit "新增物品" %>
<% end %>

app/views/goods/edit.html.erb
<%= form_for @good.becomes(Good) ,:url => good_path(@good), :method => :patch do |f| %>
<div class="col-sm-offset-3 col-sm-6 new-good">
  <div class="form-group">
    <%= f.label t(:name) %>
    <%= f.text_field :name , :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :type, "我有東東想要" %>
    <%= f.select :type, { "送" => Giving.name, "借人" => Lending.name, "徵求" => Wanting.name} %>
    <%= f.collection_select(:category_id, Category.all, :id, :name,:prompt => "東東類別" )%>
    <%= check_box_tag :status, "1"%>顯示<%= @good.status %>
  </div>
  <div class="form-group">
    <%= f.label :area, "地區" %>
    <%= f.text_field :area , :class => "form-control" %>
  </div>
  上傳照片<%= f.file_field :picture %>
  <% if @good.picture_file_name %>
    <div class="topic-img">
      <%= image_tag @good.picture.url(:medium) %>
    </div>
    <%= check_box_tag :delete_pic,"1"%>刪除照片
  <% end %>
  <div class="form-group">
    <%= f.label :description, "說明" %>
    <%= f.text_area :description , :class => "form-control" %>
  </div>
    <%= f.submit "修改東東" , :class => "btn btn-info"%>
  <% end %>
  <%= link_to "返回主頁", goods_path, :class => "btn btn-default" %>
</div>

app/views/goods/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="title">漂泊ㄟ東東</h1>
    <p class="sub-title">這是一個讓你把用不到的東東送到需要的人手上的平台</p>
    <p class="sub-title">讓東東出去漂流，幫助更多需要它的人</p>
  </div>
</div>
<h1></h1>
<%= link_to "新增東東", new_good_path, :class => "btn btn-success"%>
<table class="table">
  <thead class="thead-default">
    <tr>
      <td>我有東東想...</td>
      <td></td>
      <td>東東名稱</td>
      <td>東東地區</td>
      <td>東東說明</td>
      <td>發文者</td>
      <td>發文時間</td>
      <td>東東狀態</td>
    </tr>
  </thead>
  <tbody>
    <% @goods.each do |g| %>
  <% if g.status != nil %>
    <tr class="active">
  <% else %>
    <tr>
  <% end %>
      <td><%= t(g.type) %></td>
      <td class="list-img"><%= image_tag g.picture.url(:thumb) %></td>
      <td class="mw120"><%= link_to g.name, good_path(g) %></td>
      <td><%= g.area %></td>
      <td class="mw250"><%= g.description %></td>
      <td><%= g.user.name %></td>
      <td><%= g.created_at.localtime.to_s(:db) %></td>
      <td><%= g.status %></td>
    <%if current_user == g.user%>
      <td><%= link_to "", edit_good_path(g), :class =>"btn btn-info glyphicon glyphicon-pencil" %></td>
      <td><%= link_to "", good_path(g), :method => :delete, :class =>"btn btn-danger glyphicon glyphicon-trash" %></td>
    <% else %>
      <td></td>
      <td></td>
    <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @goods %>

app/views/goods/new.html.erb
<%= form_for @good.becomes(Good) ,:url => goods_path do |f| %>
<div class="col-sm-offset-3 col-sm-6 new-good">
  <div class="form-group">
    <%= f.label t(:name) %>
    <%= f.text_field :name , :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :type, "我有東東想要" %>
    <%= f.select :type, { "送" => Giving.name, "借人" => Lending.name, "徵求" => Wanting.name} %>
    <%= f.collection_select(:category_id, Category.all, :id, :name,:prompt => "東東類別" )%>
  </div>
  <div class="form-group">
    <%= f.label :area, "地區" %>
    <%= f.text_field :area , :class => "form-control" %>
  </div>
  上傳照片<%= f.file_field :picture %>
  <div class="form-group">
    <%= f.label :description, "說明" %>
    <%= f.text_area :description , :class => "form-control" %>
  </div>
    <%= f.submit "新增東東" , :class => "btn btn-info"%>
  <% end %>
  <%= link_to "返回主頁", goods_path, :class => "btn btn-default" %>
</div>

app/views/goods/show.html.erb
<div class="col-sm-12">
  <div class="col-sm-8 col-sm-offset-2">
    <ul class="list-group">
      <li class="list-group-item">發文者：<%= @good.user.name %></li>
      <li class="list-group-item">東東名稱：<%= @good.name %></li>
      <li class="list-group-item">東東地區：<%= @good.area %></li>
      <li class="list-group-item">東東類別：<%= @good.category.name %></li>
      <li class="list-group-item">東東說明：<%= @good.description %></li>
    </ul>
    <h4 class="col-sm-12">真相在這邊：</h4>
    <div class="show-img"><%= image_tag @good.picture.url %></div>
    <br>
  </div>
</div>
<table class="table">
  <thead>
    <th>留言內容</th>
    <th>留言者</th>
    <th>留言時間</th>
  </thead>
  <tbody>
    <% @comments.each do |c|%>
      <tr>
      <% if current_user != @good.user && current_user != c.user %>
        <td>這是悄悄話～～</td>
      <% else %>
        <td><%=c.content%></td>
      <% end %>
        <td><%=c.user.name %></td>
        <td><%=c.created_at.localtime.to_s(:db)%></td>
        <%if current_user == c.user%>
        <td><%=link_to "", edit_good_comment_path(@good,c), :class =>"btn btn-info glyphicon glyphicon-pencil"%></td>
        <td><%=link_to "", good_comment_path(@good,c),:method =>:delete, :class =>"btn btn-danger glyphicon glyphicon-trash"%></td>
        <%end%>
      </tr>
    <%end%>
  </tbody>
</table>
<% @comment = @good.comments.build %>
<%=form_for @comment, :url => good_comments_path(@good), :method => :post do |f| %>
  <%=f.label :content,"留言"%>
  <%= check_box_tag :secret, true %> 顯示為悄悄話
  <%=f.text_area :content, :class =>"form-control"%>
  <%=f.submit "新增留言", :class =>"btn btn-primary"%>
  <%= link_to "返回主頁", goods_path, :class => "btn btn-default" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Utopia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="col-sm-12">
        <%if flash[:notice].present?%>
          <div class="alert alert-success" role="alert">
            <p style="color: green"><%=flash[:notice] %></p>
          </div>
      </div>
      <%end%>
      <div class="col-sm-12">
        <%if flash[:alert].present?%>
          <div class="alert alert-danger" role="alert">
            <p style="color: red"><%=flash[:alert] %></p>
          </div>
        <%end%>
      </div>
      <span class="login">
        <% if current_user %>
          <%= link_to "登出", auth_signout_path, :method => :post %>
          <%= current_user.name %>
          <%= image_tag( current_user.fb_image ) %>
        <% else %>
          <a href="/auth/facebook">Facebook 登入</a>
        <% end %>
      </span>
      <%= yield %>
    </div>
  </body>
</html>